config/routes.rb
Rails.application.routes.draw do
  get '/podcasts/:podcast/podcast', to: 'hosting#fetch_podcast', as: 'fetch_podcast'
  get '/mark423-player', to: 'hosting#player', as: 'player_script'
  get '/podcasts', to: 'hosting#index', as: 'podcast_list'
  get '/podcasts/:podcast/:filename', to: 'hosting#fetch_recording'
  scope '/admin' do
    resources :recordings
    resources :podcasts do
      resources :privileges
    end
    resources :users
    get '/render/player/:podcast_name', to: 'render#player', as: 'render_player'
    get '/render/:podcast_name', to: 'render#show'
    post '/switch_podcast', to: 'sessions#switch_podcast'
    get '/noprivilege', to: 'request_podcast#index'  
  end
  get '/users/me', to: 'users#me', as: 'profile'
  get '/podcasts/current', to: 'podcasts#current', as: 'current_podcast'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'recover#new'
  post '/forgot', to: 'recover#create', as: "create_recovery"
  get '/forgot/reset', to: 'recover#use', as: "use_recovery"
  post '/forgot/reset', to: 'recover#reset'
  root "recordings#index"
end

app/models/recording.rb
class Recording < ApplicationRecord
  belongs_to :podcast, touch: true
  has_one_attached :audio_file
  has_one_attached :image_file do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  before_create :set_filename
  before_update :set_filename
  before_update :set_published
  before_create :set_published
  after_update :update_filename_in_storage
  after_create :update_filename_in_storage

  scope :published, -> { where(published: true) }
  after_touch :maybe_publish

  def maybe_publish
    was_published = self.published
    self.set_published
    if was_published != self.published
      self.save
      return true
    end
    false
  end

  def set_published
    was_published = self.published
    
    self.published = self.not_published_because().length == 0
    if not was_published and self.published
      PublicationMailer.recording_published(self).deliver
    end
  end

  def not_published_because
    reasons = []
    if self.visible != true
      reasons << I18n.t("not_published_because_not_visible")
    end
    if self.speaker.blank?
      reasons << I18n.t("not_published_because_no_speaker")
    end
    if self.theme.blank?
      reasons << I18n.t("not_published_because_no_theme")
    end
    if not self.audio_file.attached?
      reasons << I18n.t("not_published_because_no_audio")
    elsif not self.audio_file.analyzed?
      reasons << I18n.t("not_published_because_audio_not_analyzed")
    end
    logger.info("REASONS: " + reasons.to_s)
    reasons
  end

  def set_filename
    self.filename = get_filename()
    if self.guid == nil
      self.guid = self.audio_link
    end
  end

  def update_filename_in_storage
    if self.audio_file.attached?
     self.audio_file.blob.update(filename: filename)
    end
  end

  def get_filename()
    uncounted_filename  = speaker[0..20].parameterize + "-" unless speaker.nil?
    uncounted_filename += theme[0..30].parameterize + "-" unless theme.nil?
    uncounted_filename += recorded_at.strftime("%Y%m%d")
    new_filename = uncounted_filename
    counter = 1
    while Recording.where(filename: new_filename).where.not(id: id).any? do
      counter += 1
      new_filename = "#{uncounted_filename}-#{counter}"
    end
    new_filename
  end

  def audio_link
    self.podcast.dir + self.filename + '.mp3'
  end

  def image_link
    self.podcast.dir + self.filename + self.image_file.filename.extension
  end

  def duration
    return nil unless self.publishable
    return self.audio_file.metadata['duration']
  end

  def publishable
    return self.audio_file.attached? && self.audio_file.analyzed?
  end
  
  def schedule_render
    self.podcast.schedule_render
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < AdminController
  include ActiveStorage::SetCurrent
  before_action :set_recording, only: %i[ show edit update destroy ]

  # GET /recordings or /recordings.json
  def index
    all_recordings = current_podcast.recordings.order(recorded_at: :desc)
    page_limit = 30
    @current_page = params[:page].to_i

    @recordings = all_recordings.offset(page_limit*@current_page).limit(page_limit)
    @next_page = @current_page + 1 if(all_recordings.count > page_limit*@current_page + page_limit)
  end

  # GET /recordings/1 or /recordings/1.json
  def show
  end

  # GET /recordings/new
  def new
    @recording = Recording.new
    @recording.visible = true
    @recording.recorded_at = Time.now()
  end

  # GET /recordings/1/edit
  def edit
  end

  # POST /recordings or /recordings.json
  def create
    @recording = Recording.new(recording_params)
    @recording.podcast_id = current_podcast.id
    
    respond_to do |format|
      if @recording.save
        format.html { redirect_to recordings_url(format: :html), notice: I18n.t("model_created", model: Recording) }
        format.json { render :show, status: :created, location: @recording }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recordings/1 or /recordings/1.json
  def update
    respond_to do |format|
      if @recording.update(recording_params)
        format.html { redirect_to recordings_url(format: :html), notice: I18n.t("model_updated", model: Recording) }
        format.json { render :show, status: :ok, location: @recording }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recording.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recordings/1 or /recordings/1.json
  def destroy
    @recording.destroy

    respond_to do |format|
      format.html { redirect_to recordings_url(format: :html), notice: I18n.t("model_destroyed", model: Recording) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recording
      @recording = Recording.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def recording_params
      params.require(:recording).permit(:speaker, :theme, :recorded_at, :visible, :description, :audio_file, :image_file)
    end
end

app/helpers/recordings_helper.rb
module RecordingsHelper
  def recording_duration(recording)
    if recording.audio_file.analyzed?
      return ActiveSupport::Duration.build(recording.audio_file.metadata['duration'].round()).inspect
    else
      return "Unknown"
    end
  end
end

app/views/recordings/_form.html.erb
<% if recording.published == false %>
  <div class='warning-banner'>
    <div class='title'>
    <%= t(:this_recording_is_not_published_because) %>:
    </div>
    <ul>
    <% recording.not_published_because.each do |reason| %>
    <li><%=reason%></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: recording) do |form| %>
  <% if recording.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recording.errors.count, "error") %> <%=t("probihited_saved")%>:</h2>

      <ul>
        <% recording.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :speaker, style: "display: block" %>
    <%= form.text_field :speaker %>
  </div>

  <div>
    <%= form.label :theme, style: "display: block" %>
    <%= form.text_field :theme %>
  </div>

  <div>
    <%= form.label :recorded_at, style: "display: block" %>
    <%= form.datetime_field :recorded_at, step: :any %>
  </div>

  <div>
    <%= form.label :visible, style: "display: block" %>
    <%= form.check_box :visible %>
  </div>

  <div>
    <%= form.label :audio_file, style: "display: block" %>
    <% if recording.audio_file.attached? %>
    <div class='update-audio'>
      <span class='green'>✓</span><%= t(:audio_file_present)%> <br/>
      <span><%= t(:update)%>:</span> <%= form.file_field :audio_file, accept: 'audio/mp3' %><br/>
      <audio controls><source src='<%=recording.audio_file.url %>'></audio>
      <%=link_to t(:download), recording.audio_file, class: :download_audio %> </span><br/>
      </div>
      
    <% else %>
      <%= form.file_field :audio_file, accept: 'audio/mp3' %>
    <% end %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
   <div>
    <%= form.label :image_file, style: "display: block" %>
   <% if recording.image_file.attached? %>
       <span class='green'>✓</span><span><%= t(:image_file_present)%></span>
       <span><%=t(:update)%>:</span>
    <% end %>
    <%= form.file_field :image_file, accept: 'image/png,image/gif,image/jpeg' %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recordings/_recording.html.erb
<tr>
  <% link_td recording, :speaker do %>
    <%=recording.speaker%>&nbsp;-&nbsp;<span class='theme'><%=recording.theme%></span>
  <% end %>

  <td class='date'><%=format_date(recording.recorded_at)%></td>
  <td class='published'>
    <% if recording.published%>
      <%= inline_svg_tag 'check.svg', :class => :ok, :title => t(:published) %>
    <% else %>
    <%= inline_svg_tag 'warning.svg', :class => :warning, :title => t(:not_published) %>
    <% end %>
  </td>
  <td class='actions'>
    <%= link_to recording, data: { "turbo-method": :delete, :turbo_confirm => 'Are you sure?' }, title: t(:delete)  do %>
      <%= inline_svg_tag 'delete.svg' %>
    <% end %>
  </td>
</tr>

app/views/recordings/edit.html.erb
<h1><%=t(:model_editting, model: Recording)%></h1>

<%= render "form", recording: @recording %>

<br>

<div>
  <%= link_to t(:model_back_to_index, model: Recording), recordings_path %>
</div>

app/views/recordings/index.html.erb
<h1><%=t(:recordings)%></h1>

<%= link_to t(:model_new, model: Recording), new_recording_path %>

<table id="recordings">
  <%= render partial: "recordings/recording", collection: @recordings %>
</table>
<%= turbo_frame_tag "load_more", src: recordings_path(format: :turbo_stream, params: {page: 1}) %>

app/views/recordings/index.turbo_stream.erb
<%= turbo_stream.append "recordings" do %>
  <%= render partial: "recordings/recording", collection: @recordings %>
<% end %>

<% if @next_page.present? %>
    <%= turbo_stream.replace "load_more" do %>
        <%= turbo_frame_tag "load_more", src: recordings_path(page: @next_page, format: :turbo_stream), loading: :lazy %>
    <% end %>
<% end %>

app/views/recordings/new.html.erb
<h1><%=t(:model_new, model: Recording)%></h1>

<%= render "form", recording: @recording %>

<br>

<div>
  <%= link_to t(:model_back_to_index, model: Recording), recordings_path %>
</div>

app/views/recordings/show.html.erb
<%= render @recording %>

<div>
  <%= link_to t(:model_edit, model: Recording), edit_recording_path(@recording) %> |
  <%= link_to t(:model_back_to_index, model: Recording), recordings_path %>

  <%= button_to t(:model_destroy, model: Recording), @recording, method: :delete %>
</div>