config/routes.rb
Rails.application.routes.draw do
  get '/podcasts/:podcast/podcast', to: 'hosting#fetch_podcast', as: 'fetch_podcast'
  get '/mark423-player', to: 'hosting#player', as: 'player_script'
  get '/podcasts', to: 'hosting#index', as: 'podcast_list'
  get '/podcasts/:podcast/:filename', to: 'hosting#fetch_recording'
  scope '/admin' do
    resources :recordings
    resources :podcasts do
      resources :privileges
    end
    resources :users
    get '/render/player/:podcast_name', to: 'render#player', as: 'render_player'
    get '/render/:podcast_name', to: 'render#show'
    post '/switch_podcast', to: 'sessions#switch_podcast'
    get '/noprivilege', to: 'request_podcast#index'  
  end
  get '/users/me', to: 'users#me', as: 'profile'
  get '/podcasts/current', to: 'podcasts#current', as: 'current_podcast'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'recover#new'
  post '/forgot', to: 'recover#create', as: "create_recovery"
  get '/forgot/reset', to: 'recover#use', as: "use_recovery"
  post '/forgot/reset', to: 'recover#reset'
  root "recordings#index"
end

app/models/privilege.rb
class Privilege < ApplicationRecord
  enum :role, [:viewer, :editor, :manager]

  belongs_to :user
  belongs_to :podcast
end

app/controllers/privileges_controller.rb
class PrivilegesController < AdminController
  before_action :set_privilege, only: %i[ show edit update destroy ]
  before_action :set_podcast
 
  # GET /privileges or /privileges.json
  def index
    @privileges = @podcast.privileges
  end

  # GET /privileges/1 or /privileges/1.json
  def show
  end

  # GET /privileges/new
  def new
    @privilege = Privilege.new
  end

  # GET /privileges/1/edit
  def edit
  end

  # POST /privileges or /privileges.json
  def create
    @privilege = Privilege.new(privilege_params)

    respond_to do |format|
      if @privilege.save
        format.html { redirect_to podcast_privileges_url(@podcast), notice: I18n.t("model_created", model: Privilege) }
        format.json { render :show, status: :created, location: @privilege }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @privilege.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /privileges/1 or /privileges/1.json
  def update
    respond_to do |format|
      if @privilege.update(privilege_params)
        format.html { redirect_to podcast_privileges_url(@podcast), notice: I18n.t("model_updated", model: Privilege) }
        format.json { render :show, status: :ok, location: @privilege }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @privilege.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /privileges/1 or /privileges/1.json
  def destroy
    @privilege.destroy

    respond_to do |format|
      format.html { redirect_to podcast_privileges_url(@podcast), notice: I18n.t("model_destroyed", model: Privilege) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_privilege
      @privilege = Privilege.find(params[:id])
    end

    def set_podcast
      @podcast = Podcast.find(params[:podcast_id])
    end

    # Only allow a list of trusted parameters through.
    def privilege_params
      params.require(:privilege).permit(:user_id, :podcast_id, :role)
    end
end

app/helpers/privileges_helper.rb
module PrivilegesHelper
end

app/views/privileges/_form.html.erb
<%= form_with(model: [@podcast, privilege]) do |form| %>
  <% if privilege.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(privilege.errors.count, "error") %> <%=t("probihited_saved")%>:</h2>

      <ul>
        <% privilege.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select(:user_id, User.all, :id, :full_name) %>
  </div>

  <div>
    <%= form.label :podcast_id, style: "display: block" %>
    <%= form.collection_select(:podcast_id, Podcast.all, :id, :name) %>
    
  </div>

  <div>
    <%= form.label :role, style: "display: block" %>
    <%= form.select :role, options_for_select(enum_to_dict(Privilege.roles)) %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/privileges/_privilege.html.erb
<div id="<%= dom_id privilege %>">
  <p>
    <strong>User:</strong>
    <%= privilege.user.full_name %>
  </p>

  <p>
    <strong>Podcast:</strong>
    <%= privilege.podcast.name %>
  </p>

  <p>
    <strong>Role:</strong>
    <%= privilege.role %>
  </p>

</div>

app/views/privileges/edit.html.erb
<h1><%=t(:model_editting, model: Privilege)%></h1>

<%= render "form", privilege: @privilege %>

<br>

<div>
  <%= link_to t(:model_back_to_index, model: Privilege), podcast_privileges_path(@podcast) %>
</div>

app/views/privileges/index.html.erb
<h1><%=t(:privileges)%> for <%=@podcast.name %></h1>

<%= link_to t(:model_new, model: Privilege), new_podcast_privilege_path(@podcast) %>

<table>
  <% @privileges.each do |privilege| %>
    <tr>
    <% link_td_to_path  edit_podcast_privilege_path(@podcast, privilege), :username do %>
      <%=privilege.user.full_name%>
    <% end %>
    <% link_td_to_path  edit_podcast_privilege_path(@podcast, privilege), :role do %>
      <%=privilege.role%>
    <% end %>
    <td class='actions'>
      <%= link_to  podcast_privilege_path(@podcast, privilege), data: { "turbo-method": :delete, :turbo_confirm => 'Are you sure?' }, title: t(:delete)  do %>
        <%= inline_svg_tag 'delete.svg' %>
      <% end %>
    </td>
    </tr>
  <% end %>
</table>

app/views/privileges/new.html.erb
<h1><%=t(:model_new, model: Privilege)%></h1>

<%= render "form", privilege: @privilege %>

<br>

<div>
  <%= link_to t(:model_back_to_index, model: Privilege), podcast_privileges_path(@podcast) %>
</div>

app/views/privileges/show.html.erb
<%= render @privilege %>

<div>
  <%= link_to t(:model_edit, model: Privilege),edit_podcast_privilege_path(@podcast, @privilege) %> |
  <%= link_to t(:model_back_to_index, model: Privilege), podcast_privileges_path(@podcast) %>

  <%= button_to t(:model_destroy, model: Privilege), podcast_privilege_path(@podcast, @privilege), method: :delete %>
</div>