config/routes.rb
Rails.application.routes.draw do
  get '/podcasts/:podcast/podcast', to: 'hosting#fetch_podcast', as: 'fetch_podcast'
  get '/mark423-player', to: 'hosting#player', as: 'player_script'
  get '/podcasts', to: 'hosting#index', as: 'podcast_list'
  get '/podcasts/:podcast/:filename', to: 'hosting#fetch_recording'
  scope '/admin' do
    resources :recordings
    resources :podcasts do
      resources :privileges
    end
    resources :users
    get '/render/player/:podcast_name', to: 'render#player', as: 'render_player'
    get '/render/:podcast_name', to: 'render#show'
    post '/switch_podcast', to: 'sessions#switch_podcast'
    get '/noprivilege', to: 'request_podcast#index'  
  end
  get '/users/me', to: 'users#me', as: 'profile'
  get '/podcasts/current', to: 'podcasts#current', as: 'current_podcast'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'recover#new'
  post '/forgot', to: 'recover#create', as: "create_recovery"
  get '/forgot/reset', to: 'recover#use', as: "use_recovery"
  post '/forgot/reset', to: 'recover#reset'
  root "recordings#index"
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  has_many :privileges, dependent: :delete_all
  has_many :users, through: :privileges
  has_many :recordings, dependent: :destroy
  validates :shortname, presence: true, uniqueness: true
  validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP
  validate :validate_category
  attr_accessor :skip_callbacks

  has_one_attached :image_file do |attachable|
    attachable.variant :thumb, resize_to_limit: [100, 100]
  end
  has_one_attached :rss_file
  has_one_attached :js_file

  after_commit :schedule_render, on: [:create, :update],  unless: :skip_callbacks
  #after_touch :schedule_render, unless: :skip_callbacks
  after_initialize :empty_category

  def empty_category
    if self.category.nil?
      self.category = '{}'
    end
  end

  def visible_recordings
    self.recordings.where(published: true).order(recorded_at: :desc).limit(self.max_recordings)
  end

  def self.categories
    return @categories unless @categories.nil?
    filename = File.join(Rails.root, 'config', 'categories.yml')
    @categories = YAML.load(File.open(filename))
    @categories
  end

  def validate_category
    begin
      JSON.parse category
    rescue
      errors.add :category, "Invalid JSON string"
    end
    true
  end

  def parsed_category
    JSON.parse category rescue {}
  end     

  def each_category
    parsed_category.each_pair do |category, sub_categories|
      yield(category, sub_categories)
    end
  end

  def dir
    "#{Rails.application.config.podcast_host}/#{self.shortname}/"
  end

  def rss_link
    self.dir + "podcast.rss"
  end

  def js_link
    self.dir + "podcast.js"
  end

  def picture_link
    self.dir + "podcast." + self.image_file.filename.extension
  end

  def schedule_render
    logger.info("SCHEDULING RENDER")
    GeneratePodcastJob.perform_later self, self.updated_at
  end

  def self.languages
    {
      :en => "English",
      :nl => "Nederlands",
      :de => "Deutsch"
    }
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < AdminController
  before_action :set_podcast, only: %i[ show edit update destroy ]
  before_action :authorized_admin, except: [ :current, :update ]
  
  # GET /podcasts or /podcasts.json
  def index
    @podcasts = Podcast.all
  end

  # GET /podcasts/1 or /podcasts/1.json
  def show
  end

  # GET /podcasts/new
  def new
    @podcast = Podcast.new
  end

  # GET /podcasts/1/edit
  def edit
  end

  def current
    unless current_role == 'manager'
      raise ApplicationController::NotAuthorized
    end
    @podcast = current_podcast
    render :edit
  end

  # POST /podcasts or /podcasts.json
  def create
    @podcast = Podcast.new(podcast_params)

    respond_to do |format|
      if @podcast.save
        format.html { redirect_to podcasts_url(), notice: I18n.t("model_created", model: Podcast) }
        format.json { render :show, status: :created, location: @podcast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /podcasts/1 or /podcasts/1.json
  def update
    unless current_user.is_admin? || (current_role == 'manager' && current_podcast == @podcast)
      format.html { render :new, status: :access_denied }
      format.json { render json: {'access': 'denied'}, status: :access_denied }
    end
    if current_user.is_admin?
      redirect = podcast_url(@podcast)
    else
      redirect = current_podcast_path
    end
    respond_to do |format|
      if @podcast.update(podcast_params)
        format.html { redirect_to podcasts_url, notice: I18n.t("model_updated", model: Podcast) }
        format.json { render :show, status: :ok, location: @podcast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @podcast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /podcasts/1 or /podcasts/1.json
  def destroy
    @podcast.destroy

    respond_to do |format|
      format.html { redirect_to podcasts_url, notice: I18n.t("model_destroyed", model: Podcast) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_podcast
      @podcast = Podcast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def podcast_params
      params.require(:podcast).permit(:name, :shortname, :website, :copyright, :max_recordings, :author, :email, :description, :language, :keywords, :image_file, :explicit, :category)
    end
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_category_chooser.html.erb
<%
def category_id(category)
  category = category.gsub("&", "")
  category = category.gsub(" ", "")
end

def contains_key(haystack, needle)
  if haystack.is_a? Array
    return haystack.include? needle
  elsif haystack.is_a? Hash
    return haystack.keys.include? needle
  else
    return false
  end
end

def render_category(category, selected_categories=nil)
  key = (category.is_a? Hash) ? category.keys.first : category
  selected = contains_key(selected_categories, key)
  selected_sub_categories = selected_categories[key] rescue nil
  render_category_checkbox key, '', 0, selected
  if category.is_a? Hash
    category[key].each do |sub_category|
      selected = selected_sub_categories.include? sub_category rescue false
      render_category_checkbox(key, sub_category, 1, selected)
    end
  end
end

def render_category_checkbox(category, sub_category, level, selected)
  name = (sub_category.blank?) ? category : sub_category
  handle = 'chkCategory-' + category_id(category)
  handle += '-' + category_id(sub_category) unless sub_category.blank?
  sub_handle = 'chkSubCat-' + category_id(category) unless sub_category.blank?
  concat raw '&nbsp;&nbsp;' * level
  concat tag("input", :type => 'checkbox', :value => "#{category},#{sub_category}", :class => "category-check #{sub_handle}", :checked => selected, :id => handle)
  concat content_tag("label", name, :for => handle) 
  concat tag("br")
end

%>
<div class='category-chooser closed'>
  <span class='select'>Click to select categories
    <b><span id='num-selected'>(<%=selected_categories.flatten.flatten.size rescue 0%></span> selected)</b></span>
  <div class='categories'>
     <% Podcast.categories.each do |category| 
       render_category category, selected_categories
     end %>
  </div>
</div>
<%= f.hidden_field :category, :class => 'category_selector' %>

app/views/podcasts/_form.html.erb
<%= form_with(model: podcast) do |form| %>
  <% if podcast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(podcast.errors.count, t("error")) %> <%=t("probihited_saved")%>:</h2>

      <ul>
        <% podcast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% unless  podcast.new_record? %>
  <div class='podcast-url'>
  <strong>Podcast url:</strong> <%=fetch_podcast_url(podcast.shortname, format: :rss)%>
  </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :website, style: "display: block" %>
    <%= form.text_field :website %>
  </div>

  <div>
    <%= form.label :shortname, style: "display: block" %>
    <%= form.text_field :shortname %>
  </div>

  <div>
    <%= form.label :copyright, style: "display: block" %>
    <%= form.text_field :copyright %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>
<div>
    <%= form.label :max_recordings, style: "display: block" %>
    <%= form.number_field :max_recordings %>
  </div>
  <div>
    <%= form.label :keywords, style: "display: block" %>
    <%= form.text_field :keywords %>
  </div>
   <div>
    <% if podcast.image_file.attached?  %>
      <%= image_tag podcast.image_file.variant(:thumb) %>
    <% end %>
    <%= form.label :image_file, style: "display: block" %>
    <%= form.file_field :image_file, accept: 'image/png,image/gif,image/jpeg' %>
  </div>
  <div class="field">
    <%= form.label :language %><br />
    <%= form.select :language, Podcast.languages.map{|a,b|[b,a]} %>
  </div>
   <div class="field">
    <%= form.label :explicit %><br />
    <%= form.check_box :explicit %>
  </div>
  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>
  <div class="field">
    <%= form.label :category %><br />
    <%= render :partial => 'category_chooser', :locals => {:selected_categories => @podcast.parsed_category, :f => form} %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/podcasts/_podcast.html.erb
<div id="<%= dom_id podcast %>" class="podcast card">
    <% if podcast.image_file.attached?  %>
      <%= image_tag podcast.image_file.variant(:thumb) %>
    <% else %>
      <%= image_tag "placeholder.png" %>
    <% end %>
  <div class='data'>
    <p class='title'><%= podcast.name %> (<%= podcast.shortname %>) - <%=podcast.email%></p>
    <p class='description'>
      <%= podcast.description%>
    </p>
  </div>
  <div class='actions'>
    <%= link_to t(:edit), edit_podcast_path(podcast) %>
    <%= link_to t(:privileges), podcast_privileges_path(podcast) %>
    <%= link_to t(:destroy), podcast, data: { "turbo-method": :delete, :turbo_confirm => 'Are you sure?'}, title: t(:delete) %>
  </div>
</div>

app/views/podcasts/edit.html.erb
<h1>Editing podcast</h1>

<%= render "form", podcast: @podcast %>

<br>
<% if current_user.is_admin? %>
<div>
  <%= link_to t(:model_back_to_index, model: Podcast), podcasts_path %>
</div>
<% end %>

app/views/podcasts/index.html.erb
<h1><%=t(:podcasts)%></h1>

<%= link_to t(:model_new, model: Podcast), new_podcast_path %>
<p></p>
<div id="podcasts">
  <% @podcasts.each do |podcast| %>
    <%= render podcast %>
  <% end %>
</div>

app/views/podcasts/new.html.erb
<h1><%=t(:model_new, model: Podcast)%></h1>

<%= render "form", podcast: @podcast %>

<br>

<div>
  <%= link_to t(:model_back_to_index, model: Podcast), podcasts_path %>
</div>

app/views/podcasts/show.html.erb
<%= render @podcast %>

<h2>Privileges</h2>
<% @podcast.privileges.each do |privilege| %>
    <%= render privilege %>
<% end %>

<div>
  <%= link_to t(:model_edit, model: Podcast), edit_podcast_path(@podcast) %> |
  <%= link_to t(:privileges_for_this_podcast), podcast_privileges_path(@podcast) %> |
  <%= link_to t(:model_back_to_index, model: Podcast), podcasts_path %>

  <%= button_to t(:model_destroy, model: Podcast), @podcast, method: :delete %>
</div>