config/routes.rb
Rails.application.routes.draw do
  get '/podcasts/:podcast/podcast', to: 'hosting#fetch_podcast', as: 'fetch_podcast'
  get '/mark423-player', to: 'hosting#player', as: 'player_script'
  get '/podcasts', to: 'hosting#index', as: 'podcast_list'
  get '/podcasts/:podcast/:filename', to: 'hosting#fetch_recording'
  scope '/admin' do
    resources :recordings
    resources :podcasts do
      resources :privileges
    end
    resources :users
    get '/render/player/:podcast_name', to: 'render#player', as: 'render_player'
    get '/render/:podcast_name', to: 'render#show'
    post '/switch_podcast', to: 'sessions#switch_podcast'
    get '/noprivilege', to: 'request_podcast#index'  
  end
  get '/users/me', to: 'users#me', as: 'profile'
  get '/podcasts/current', to: 'podcasts#current', as: 'current_podcast'
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'
  get '/forgot', to: 'recover#new'
  post '/forgot', to: 'recover#create', as: "create_recovery"
  get '/forgot/reset', to: 'recover#use', as: "use_recovery"
  post '/forgot/reset', to: 'recover#reset'
  root "recordings#index"
end

app/views/layouts/_navigation.html.erb
<nav>
  <ul>
    <li class='logo'>Mark4:23</li>
    <% if current_role == 'manager' %>
    <li><%= link_to t("podcast"), current_podcast_path %></li>
    <% end %>
    <% if current_user.is_admin? %>
    <li><%= link_to t("users"), users_path %></li>
    <li><%= link_to t("podcasts"), podcasts_path %></li>
    <% end %>
    <% unless current_podcast.nil? %>
      <li><%= link_to t("recordings"), recordings_path %></li>
    <% end %>
    <li class='split'><%=current_user.full_name %>(<%=link_to "Me", profile_path%>) (<%=current_role %>)</li>
    <li>
    <% unless current_podcast.nil? %>
      <%= form_tag switch_podcast_path, {:class => "inline-form"} do %>
        <%=select :podcast, :id, my_podcasts, {:selected => current_podcast.id }, :onchange => 'this.form.submit()' %>
      <% end %>
    <% end %>
    </li> 
    <!--<li> <%= inline_svg_tag 'darkmode.svg', class: :darkmode %></li>-->
    <li><%= link_to t("logout"), logout_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mark423</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "simple" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    
  </head>

  <body>
    <%= render "layouts/navigation" %>
     <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: build_alert_classes(type) %>
    <% end %>
    <div class='<%=current_controller%> <%=current_action%>'>
    <%= yield %>
    </div>
    <%=javascript_importmap_tags %>
  </body>
</html>

app/views/layouts/clean.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mark423</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "simple" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= yield :header_content %>
    
  </head>

  <body>
   <% flash.each do |type, msg| %>
      <%= content_tag :div, msg, class: build_alert_classes(type) %>
    <% end %>
    <div class='<%=current_controller%> <%=current_action%>'>
    <%= yield %>
    </div>
  </body>
</html>